# Auto-generated by /Users/tclose/git/workflows/nipype2pydra/nipype2pydra/package.py, do not edit as it will be overwritten

src_pkg_version = "24.1.0"
nipype2pydra_version = "0.4.3"
post_release = "2410043"
        